---
kind: pipeline
type: docker
name: build

steps:
  - name: build python
    image: python:3.5-buster
    commands:
      - apt-get update && apt-get install -y protobuf-compiler
      - python setup.py sdist bdist_wheel

  - name: Deploy distribution
    image: kroniak/ssh-client
    when:
      event:
        - tag
        - promote
    environment:
      SSH_USER:
        from_secret: ssh_user
      SSH_KEY:
        from_secret: ssh_key
    commands:
      # Fail on attempted overwrite: - chmod -w dist/*
      - mkdir /root/.ssh && echo "$SSH_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
      - scp -o StrictHostKeyChecking=no dist/* $SSH_USER@ccs1.tkn.tu-berlin.de:/srv/www/intern.ccs-labs.org/mirror/python-packages/evi-asm-protocol/

---
kind: pipeline
type: docker
name: lint

steps:
  - name: lint
    image: python:3.5-buster
    commands:
      - apt-get update && apt-get install -y protobuf-compiler
      - mkdir -p /tmp/pgl
      - cd /tmp/pgl
      - wget https://github.com/ckaznocha/protoc-gen-lint/releases/download/v0.2.1/protoc-gen-lint_linux_amd64.zip
      - unzip protoc-gen-lint_linux_amd64.zip
      - cp protoc-gen-lint /usr/local/bin
      - cd -
      - cd protobuf
      - protoc --lint_out=. asmp.proto
---
kind: pipeline
type: docker
name: docs

steps:
  - name: protoc-gen-docs
    image: pseudomuto/protoc-gen-doc
    commands:
      - mkdir -p out
      - find protobuf -name "*.proto" -print0 | xargs -0 protoc --doc_out=out --doc_opt=html,protoc-gen.html -I protobuf
      - find protobuf -name "*.proto" -print0 | xargs -0 protoc --doc_out=out --doc_opt=markdown,protoc-gen.md -I protobuf
      - sed -i -n '/## Scalar Value Types/q;p' out/protoc-gen.md
      - echo '# Version\n' >> out/protoc-gen.md
      - echo 'Commit ${DRONE_COMMIT_SHA:0:8}' >> out/protoc-gen.md
      - echo 'Date ' $(date -Iseconds) >> out/protoc-gen.md

  - name: wiki-upload
    image: alpine/git
    commands:
      - echo "Username '$DRONE_ASKPASS_USERNAME'"
      - echo "machine webgit.ccs-labs.org login $DRONE_ASKPASS_USERNAME password $DRONE_ASKPASS_PASSWORD" > ~/.netrc
      - git clone ${DRONE_GIT_HTTP_URL/.git/.wiki.git} /wiki
      - mv out/protoc-gen.md /wiki/
      - git -C /wiki add protoc-gen.md
      - git -C /wiki commit -m"Update auto-generated protobuf docs for commit ${DRONE_COMMIT_SHA:0:8}"
      - git -C /wiki push
